// General
export const APP_LOAD = 'APP_LOAD'
export const REDIRECT = 'REDIRECT'
export const ASYNC_START = 'ASYNC_START'
export const SET_PAGE = 'SET_PAGE'

// Auth
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH'
export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'
export const LOGOUT = 'LOGOUT'
export const AUTH_PAGE_UNLOADED = 'AUTH_PAGE_UNLOADED'

// Home
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED'
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED'
export const APPLY_TAG_FILTER = 'APPLY_TAG_FILTER'
export const TOGGLE_TYPES = 'TOGGLE_TYPES'

// Home - Request
export const REQUEST_PAGE_LOADED = 'REQUEST_PAGE_LOADED'
export const REQUEST_PAGE_UNLOADED = 'REQUEST_PAGE_UNLOADED'
export const CHANGE_TAB = 'CHANGE_TAB'

// Home - Gift
export const GIFT_PAGE_LOADED = 'GIFT_PAGE_LOADED'
export const GIFT_PAGE_UNLOADED = 'GIFT_PAGE_UNLOADED'

// Request
export const SUBMIT_REQUEST = 'SUBMIT_REQUEST'
export const DELETE_REQUEST = 'DELETE_REQUEST'
export const WISH_REQUEST = 'WISH_REQUEST'
export const UNWISH_REQUEST = 'UNWISH_REQUEST'
export const TAKE_REQUEST = 'TAKE_REQUEST'
export const UNTAKE_REQUEST = 'UNTAKE_REQUEST'
export const HELPER_LOADED = 'HELPER_LOADED'
export const CONFIRM_HELPER = 'CONFIRM_HELPER'
export const END_REQUEST = 'END_REQUEST'

// Comment
export const ADD_COMMENT = 'ADD_COMMENT'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'

// Gift
export const SUBMIT_GIFT = 'SUBMIT_GIFT'
export const DELETE_GIFT = 'DELETE_GIFT'
export const UPDATE_GIFT = 'UPDATE_GIFT'
export const SWITCH_ACCESS_GIFT = 'SWITCH_ACCESS_GIFT'

// Profile
export const PROFILE_PAGE_LOADED = 'PROFILE_PAGE_LOADED'
export const PROFILE_PAGE_UNLOADED = 'PROFILE_PAGE_UNLOADED'
export const FOLLOW_USER = 'FOLLOW_USER'
export const UNFOLLOW_USER = 'UNFOLLOW_USER'
export const SWITCH_TAKINGS = 'SWITCH_TAKINGS'
export const SAVE_SETTINGS = 'SAVE_SETTINGS'

// Request Editor
export const REQUEST_EDITOR_LOADED = 'REQUEST_EDITOR_LOADED'
export const UPDATE_FIELD_REQUEST = 'UPDATE_FIELD_REQUEST'
export const REQUEST_EDITOR_UNLOADED = 'REQUEST_EDITOR_UNLOADED'
export const ADD_TAG_REQUEST = 'ADD_TAG_REQUEST'
export const REMOVE_TAG_REQUEST = 'REMOVE_TAG_REQUEST'

// Gift Editor
export const UPDATE_FIELD_GIFT = 'UPDATE_FIELD_GIFT'
export const GIFT_EDITOR_LOADED = 'GIFT_EDITOR_LOADED'
export const GIFT_EDITOR_UNLOADED = 'GIFT_EDITOR_UNLOADED'
export const ADD_TAG_GIFT = 'ADD_TAG_GIFT'
export const REMOVE_TAG_GIFT = 'REMOVE_TAG_GIFT'
